### ISSUE TITLE
Not available

### ISSUE THREAD

**Issue by kirtar-tw** [Auxilor/EcoCrates#19]
[20:51:41 WARN]: java.lang.reflect.InvocationTargetException
[20:51:41 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:51:41 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[20:51:41 WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20:51:41 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[20:51:41 WARN]:        at eco-6.34.0-all.jar//com.willfp.eco.internal.config.EcoConfigHandler.callUpdate(EcoConfigHandler.kt:25)
[20:51:41 WARN]:        at eco-6.34.0-all.jar//com.willfp.eco.core.EcoPlugin.reload(EcoPlugin.java:493)
[20:51:41 WARN]:        at eco-6.34.0-all.jar//com.willfp.eco.core.EcoPlugin.reloadWithTime(EcoPlugin.java:511)
[20:51:41 WARN]:        at EcoCrates_v1.6.4.jar//com.willfp.ecocrates.commands.CommandReload.onExecute(CommandReload.kt:18)
[20:51:41 WARN]:        at eco-6.34.0-all.jar//com.willfp.eco.core.command.impl.HandledCommand.handle(HandledCommand.java:147)
[20:51:41 WARN]:        at eco-6.34.0-all.jar//com.willfp.eco.core.command.impl.HandledCommand.handle(HandledCommand.java:132)
[20:51:41 WARN]:        at eco-6.34.0-all.jar//com.willfp.eco.core.command.impl.PluginCommand.onCommand(PluginCommand.java:70)
[20:51:41 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[20:51:41 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[20:51:41 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:905)
[20:51:41 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2306)
[20:51:41 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2117)
[20:51:41 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2098)
[20:51:41 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[20:51:41 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[20:51:41 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:51)
[20:51:41 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[20:51:41 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[20:51:41 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:23)
[20:51:41 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1399)
[20:51:41 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188)
[20:51:41 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.y(IAsyncTaskHandler.java:126)
[20:51:41 WARN]:        at net.minecraft.server.MinecraftServer.be(MinecraftServer.java:1376)
[20:51:41 WARN]:        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1369)
[20:51:41 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[20:51:41 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1347)
[20:51:41 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1229)
[20:51:41 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
[20:51:41 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[20:51:41 WARN]: Caused by: java.lang.LinkageError: loader constraint violation: when resolving method 'com.willfp.eco.core.gui.menu.Menu com.willfp.eco.core.gui.GUIHelperExtensions.menu(int, kotlin.jvm.functions.Function1)' the class loader 'EcoCrates_v1.6.4.jar' @28731eb3 of the current class, com/willfp/ecocrates/crate/KeyGUI, and the class loader 'eco-6.34.0-all.jar' @62f0e33f for the method's defining class, com/willfp/eco/core/gui/GUIHelperExtensions, have different Class objects for the type kotlin/jvm/functions/Function1 used in the signature (com.willfp.ecocrates.crate.KeyGUI is in unnamed module of loader 'EcoCrates_v1.6.4.jar' @28731eb3, parent loader java.net.URLClassLoader @4cdf35a9; com.willfp.eco.core.gui.GUIHelperExtensions is in unnamed module of loader 'eco-6.34.0-all.jar' @62f0e33f, parent loader java.net.URLClassLoader @4cdf35a9)
[20:51:41 WARN]:        at EcoCrates_v1.6.4.jar//com.willfp.ecocrates.crate.KeyGUI.update(KeyGUI.kt:17)
[20:51:41 WARN]:        ... 33 more

EcoCrates_v1.6.4
eco-6.34.0-all
paper-1.18.2-286

**Comment by WillFP** [comment]
update ecocrates to 1.6.5

**Comment by WillFP** [comment]
can you send the full latest.log?

**Comment by LuluxClient** [comment]
This guy looks giga dumb

**Comment by kirtar-tw** [comment]
[latest.log](https://github.com/Auxilor/EcoCrates/files/8583163/latest.log)

**Comment by WillFP** [comment]
guilds is conflicting, if you ask in the ecocrates channel on discord i'll patch your guilds jar
