### ISSUE TITLE
java.lang.NoClassDefFoundError: me/PM2/customcrates/crates/Crate

### ISSUE THREAD

**Issue by viveleroi** [Auxilor/EcoCrates#30]
**Describe the bug**

I asked in purchase-questions if EcoCrates could convert from SpecializedCrates and was told by a staff member that it could for SpecializedCrates version 2.x.x. I bought the EcoCrates plugin and put it in my server.

I'm using SpecializedCrates v2.29.11

Per the docs I left SpecializedCrates.jar in as well, booted the server, and ran the conversion command.

It threw this error:

```
[09:52:56 WARN]: Unexpected exception while parsing console command "ecocrates convert SpecializedCrates"
org.bukkit.command.CommandException: Unhandled exception executing command 'ecocrates' in plugin EcoCrates v1.12.1
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:900) ~[purpur-1.19.jar:git-Purpur-1659]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchServerCommand(CraftServer.java:863) ~[purpur-1.19.jar:git-Purpur-1659]
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:512) ~[purpur-1.19.jar:git-Purpur-1659]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.19.jar:git-Purpur-1659]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1441) ~[purpur-1.19.jar:git-Purpur-1659]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1208) ~[purpur-1.19.jar:git-Purpur-1659]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:307) ~[purpur-1.19.jar:git-Purpur-1659]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: me/PM2/customcrates/crates/Crate
        at com.willfp.ecocrates.converters.impl.SpecializedCratesConverter.convert(SpecializedCratesConverter.kt:19) ~[EcoCrates v1.12.1.jar:?]
        at com.willfp.ecocrates.commands.CommandConvert.onExecute(CommandConvert.kt:29) ~[EcoCrates v1.12.1.jar:?]
        at com.willfp.eco.core.command.impl.HandledCommand.handle(HandledCommand.java:147) ~[eco-6.36.5-all.jar:?]
        at com.willfp.eco.core.command.impl.HandledCommand.handle(HandledCommand.java:132) ~[eco-6.36.5-all.jar:?]
        at com.willfp.eco.core.command.impl.PluginCommand.onCommand(PluginCommand.java:70) ~[eco-6.36.5-all.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
        ... 9 more
Caused by: java.lang.ClassNotFoundException: me.PM2.customcrates.crates.Crate
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:153) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:105) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at com.willfp.ecocrates.converters.impl.SpecializedCratesConverter.convert(SpecializedCratesConverter.kt:19) ~[EcoCrates v1.12.1.jar:?]
        at com.willfp.ecocrates.commands.CommandConvert.onExecute(CommandConvert.kt:29) ~[EcoCrates v1.12.1.jar:?]
        at com.willfp.eco.core.command.impl.HandledCommand.handle(HandledCommand.java:147) ~[eco-6.36.5-all.jar:?]
        at com.willfp.eco.core.command.impl.HandledCommand.handle(HandledCommand.java:132) ~[eco-6.36.5-all.jar:?]
        at com.willfp.eco.core.command.impl.PluginCommand.onCommand(PluginCommand.java:70) ~[eco-6.36.5-all.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
        ... 9 more
```

**To Reproduce**
Run the command to convert from specializedcrates.

**Expected behavior**
No errors

**Screenshots**

**Server Information (please complete the following information):**
- Version: Purpur version git-Purpur-1659 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: c5dbf9c on HEAD)
- Version of plugin and eco: eco-6.36.5-all, EcoCrates v1.12.1

**Comment by WillFP** [comment]
Known since scrates 3.x.x - downgrade to 2.x.x, I can't add support due to obfuscation (PM2 trying to break things)

**Comment by viveleroi** [comment]
> I'm using SpecializedCrates v2.29.11

**Comment by viveleroi** [comment]
I already went to a new crates plugin so just leave this closed.
